"""Add FichaLevantamiento model for inventory tracking

Revision ID: a1b2c3d4e5f6
Revises: c929f0ecd872
Create Date: 2025-12-16 17:40:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = 'c929f0ecd872'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fichas_levantamiento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_siga', sa.String(length=50), nullable=False),
    sa.Column('usuario_levantamiento', sa.String(length=50), nullable=False),
    sa.Column('archivo_pdf', sa.String(length=255), nullable=False),
    sa.Column('cantidad_bienes', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_verificacion', sa.DateTime(), nullable=True),
    sa.Column('verificado_por', sa.String(length=50), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_levantamiento'], ['usuarios_app.username'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_siga')
    )
    op.create_index('ix_fichas_levantamiento_estado', 'fichas_levantamiento', ['estado'], unique=False)
    op.create_index('ix_fichas_levantamiento_fecha_creacion', 'fichas_levantamiento', ['fecha_creacion'], unique=False)
    op.create_index('ix_fichas_levantamiento_numero_siga', 'fichas_levantamiento', ['numero_siga'], unique=False)
    op.create_index('ix_fichas_levantamiento_usuario_levantamiento', 'fichas_levantamiento', ['usuario_levantamiento'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_fichas_levantamiento_usuario_levantamiento', table_name='fichas_levantamiento')
    op.drop_index('ix_fichas_levantamiento_numero_siga', table_name='fichas_levantamiento')
    op.drop_index('ix_fichas_levantamiento_fecha_creacion', table_name='fichas_levantamiento')
    op.drop_index('ix_fichas_levantamiento_estado', table_name='fichas_levantamiento')
    op.drop_table('fichas_levantamiento')
    # ### end Alembic commands ###
