"""Initial migration: create all tables from SQLAlchemy models

Revision ID: c929f0ecd872
Revises: 
Create Date: 2025-11-27 16:05:29.712290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c929f0ecd872'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ambientes')
    op.drop_table('chat')
    with op.batch_alter_table('bienes', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('codigo_patrimonial',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.alter_column('cod_barras',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('denominacion',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.alter_column('marca',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('modelo',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('serie',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('estado',
               existing_type=sa.TEXT(),
               type_=sa.String(length=1),
               existing_nullable=True)
        batch_op.alter_column('unidad_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('responsable',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('usuario_registro',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('fecha_registro',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('cal_2020',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('cal_2021',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('cal_2022',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('cal_2023',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('cal_2024',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('cal_2025',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.create_index('idx_bien_cal_2025', ['cal_2025'], unique=False)
        batch_op.create_index('idx_bien_denominacion', ['denominacion'], unique=False)
        batch_op.create_index('idx_bien_fecha', ['fecha_registro'], unique=False)
        batch_op.create_index('idx_bien_sede_estado', ['sede_id', 'estado'], unique=False)
        batch_op.create_index('idx_bien_usuario_registro', ['usuario_registro'], unique=False)
        batch_op.create_index(batch_op.f('ix_bienes_cal_2025'), ['cal_2025'], unique=True)
        batch_op.create_index(batch_op.f('ix_bienes_cod_barras'), ['cod_barras'], unique=True)
        batch_op.create_index(batch_op.f('ix_bienes_codigo_patrimonial'), ['codigo_patrimonial'], unique=True)
        batch_op.create_index(batch_op.f('ix_bienes_denominacion'), ['denominacion'], unique=False)
        batch_op.create_index(batch_op.f('ix_bienes_fecha_registro'), ['fecha_registro'], unique=False)
        batch_op.create_index(batch_op.f('ix_bienes_sede_id'), ['sede_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bienes_serie'), ['serie'], unique=True)
        batch_op.create_index(batch_op.f('ix_bienes_unidad_id'), ['unidad_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bienes_usuario_registro'), ['usuario_registro'], unique=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'sedes', ['sede_id'], ['id'])
        batch_op.create_foreign_key(None, 'unidades', ['unidad_id'], ['id'])
        batch_op.drop_column('fecha_inventario')
        batch_op.drop_column('ambiente_id')
        batch_op.drop_column('codigo_siga_2')
        batch_op.drop_column('codigo_siga_1')
        batch_op.drop_column('responsable_dni')

    with op.batch_alter_table('historial', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('usuario',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('accion',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('fecha',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.create_index('idx_historial_bien_usuario', ['bien_id', 'usuario'], unique=False)
        batch_op.create_index('idx_historial_fecha', ['fecha'], unique=False)
        batch_op.create_index(batch_op.f('ix_historial_bien_id'), ['bien_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_historial_fecha'), ['fecha'], unique=False)
        batch_op.create_index(batch_op.f('ix_historial_usuario'), ['usuario'], unique=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'bienes', ['bien_id'], ['id'])

    with op.batch_alter_table('sedes', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('nombre',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.create_index('idx_sede_nombre', ['nombre'], unique=False)
        batch_op.create_index(batch_op.f('ix_sedes_nombre'), ['nombre'], unique=False)
        batch_op.drop_column('direccion')

    with op.batch_alter_table('unidades', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('nombre',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.create_index('idx_unidad_nombre', ['nombre'], unique=False)
        batch_op.create_index(batch_op.f('ix_unidades_nombre'), ['nombre'], unique=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('sede_id')
        batch_op.drop_column('tipo')

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('usuario',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('nombre',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('rol',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_usuarios_usuario'), ['usuario'], unique=True)
        batch_op.drop_column('fecha_creacion')

    with op.batch_alter_table('usuarios_app', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.alter_column('nombre',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('rol',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               nullable=True)
        batch_op.alter_column('activo',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.create_index(batch_op.f('ix_usuarios_app_username'), ['username'], unique=False)
        batch_op.drop_column('require_password_change')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios_app', schema=None) as batch_op:
        batch_op.add_column(sa.Column('require_password_change', sa.INTEGER(), server_default=sa.text('0'), nullable=False))
        batch_op.drop_index(batch_op.f('ix_usuarios_app_username'))
        batch_op.alter_column('activo',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('rol',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('nombre',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_creacion', sa.TEXT(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_usuarios_usuario'))
        batch_op.alter_column('rol',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('nombre',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('usuario',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('unidades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('sede_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(None, 'sedes', ['sede_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_unidades_nombre'))
        batch_op.drop_index('idx_unidad_nombre')
        batch_op.alter_column('nombre',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('sedes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('direccion', sa.TEXT(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_sedes_nombre'))
        batch_op.drop_index('idx_sede_nombre')
        batch_op.alter_column('nombre',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('historial', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'bienes', ['bien_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_historial_usuario'))
        batch_op.drop_index(batch_op.f('ix_historial_fecha'))
        batch_op.drop_index(batch_op.f('ix_historial_bien_id'))
        batch_op.drop_index('idx_historial_fecha')
        batch_op.drop_index('idx_historial_bien_usuario')
        batch_op.alter_column('fecha',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('accion',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('usuario',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('bienes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('responsable_dni', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('codigo_siga_1', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('codigo_siga_2', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('ambiente_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('fecha_inventario', sa.TEXT(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'sedes', ['sede_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'ambientes', ['ambiente_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'unidades', ['unidad_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_index(batch_op.f('ix_bienes_usuario_registro'))
        batch_op.drop_index(batch_op.f('ix_bienes_unidad_id'))
        batch_op.drop_index(batch_op.f('ix_bienes_serie'))
        batch_op.drop_index(batch_op.f('ix_bienes_sede_id'))
        batch_op.drop_index(batch_op.f('ix_bienes_fecha_registro'))
        batch_op.drop_index(batch_op.f('ix_bienes_denominacion'))
        batch_op.drop_index(batch_op.f('ix_bienes_codigo_patrimonial'))
        batch_op.drop_index(batch_op.f('ix_bienes_cod_barras'))
        batch_op.drop_index(batch_op.f('ix_bienes_cal_2025'))
        batch_op.drop_index('idx_bien_usuario_registro')
        batch_op.drop_index('idx_bien_sede_estado')
        batch_op.drop_index('idx_bien_fecha')
        batch_op.drop_index('idx_bien_denominacion')
        batch_op.drop_index('idx_bien_cal_2025')
        batch_op.alter_column('cal_2025',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('cal_2024',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('cal_2023',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('cal_2022',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('cal_2021',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('cal_2020',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('fecha_registro',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('usuario_registro',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('responsable',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('unidad_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('estado',
               existing_type=sa.String(length=1),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('serie',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('modelo',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('marca',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('denominacion',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('cod_barras',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('codigo_patrimonial',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    op.create_table('chat',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('usuario', sa.TEXT(), nullable=False),
    sa.Column('rol', sa.TEXT(), nullable=True),
    sa.Column('rol_mensaje', sa.TEXT(), nullable=False),
    sa.Column('contenido', sa.TEXT(), nullable=False),
    sa.Column('fecha', sa.TEXT(), nullable=True),
    sa.Column('bien_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['bien_id'], ['bienes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ambientes',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('unidad_id', sa.INTEGER(), nullable=False),
    sa.Column('nombre', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['unidad_id'], ['unidades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unidad_id', 'nombre')
    )
    # ### end Alembic commands ###
